### ISSUE TITLE
tap_ok 1 is an odd choice 

### ISSUE THREAD

**Issue by christian-elsee** [dnmfarrell/tap.sh#3]
First, let me say that I am big fan of this effort; its the the kind of minimalism that takes skill and creativity to pull off. Second, and I do mean this with the something like affection, with a dash of parental disapointment, but the why the fuck did you use "1" as a the success argument vaue for `tap_ok`?

```sh
#!/bin/sh
...
jq check/json/correctness.json >/dev/null
tap_ok "$?" "json correctness"
```

Am I missing something? Again, I do want to stress that I appreciate your work, so apologies for the frustration. Why is an exit status of 0, not considered a valid success? Cheers

**Comment by dnmfarrell** [comment]
Yeah it was an odd choice. It was motivated by [arithmetic expansion](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_04) using C semantics:

```sh
$(( 0 > 0)) # 0
$(( 1 > 0)) # 1
```
I've changed it.

**Comment by christian-elsee** [comment]
Cheers dude! I use this in almost all of my projects, work and otherwise, so the change is much appreciated.
